import { motion } from "framer-motion";
import { Zap, Palette, Users } from "lucide-react";
import { Container, Section } from "@/components/brand/Container";

const proofPoints = [
  {
    main: "100 hours of footage.",
    sub: "Searched in seconds.",
  },
  {
    main: "Less time on repetitive editing tasks.",
    sub: "",
  },
  {
    main: "One editing environment.",
    sub: "Zero app switching.",
  },
  {
    main: "Every AI edit is yours",
    sub: "to change. Always.",
  },
];

const supportingPoints = [
  {
    icon: Zap,
    title: "Search first, scrub less",
    description: "Find exact moments from long-form footage in seconds with natural language.",
  },
  {
    icon: Palette,
    title: "One pass, full polish",
    description: "Captions, filler cleanup, rhythm alignment, and structure happen together.",
  },
  {
    icon: Users,
    title: "AI speed with human control",
    description: "Everything generated by AI remains editable on your real timeline.",
  },
];

export function Outcomes() {
  return (
    <Section className="py-24 sm:py-32">
      <Container>
        {/* Header */}
        <div className="mx-auto max-w-3xl text-center mb-20">
          <h2 className="font-display text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight text-smoke">
            Product <span className="text-white">proof</span>, not promises.
          </h2>
        </div>

        {/* Proof Points Grid - 4 columns */}
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-16">
          {proofPoints.map((point, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.08 }}
              className="flex flex-col justify-center px-6 py-8 border border-white/8 rounded-xl bg-white/[0.02] hover:bg-white/[0.04] transition-colors duration-300"
            >
              <div className="font-display text-lg sm:text-xl font-bold text-white leading-snug">
                {point.main}
              </div>
              {point.sub && (
                <div className="mt-2 text-sm text-smoke/70">
                  {point.sub}
                </div>
              )}
            </motion.div>
          ))}
        </div>

        {/* Supporting Points - 3 columns */}
        <div className="grid gap-8 sm:grid-cols-3 mt-20 pt-12 border-t border-white/5">
          {supportingPoints.map((point, i) => {
            const Icon = point.icon;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: (i + 4) * 0.08 }}
                className="flex flex-col"
              >
                <div className="flex items-center justify-start">
                  <Icon size={24} className="text-solargold flex-shrink-0" />
                </div>
                <h3 className="mt-4 font-display text-base sm:text-lg font-bold text-white">
                  {point.title}
                </h3>
                <p className="mt-2 text-sm text-smoke/70 leading-relaxed">
                  {point.description}
                </p>
              </motion.div>
            );
          })}
        </div>
      </Container>
    </Section>
  );
}
