import { motion } from "framer-motion";
import { Zap, Palette, Users } from "lucide-react";
import { Container, Section } from "@/components/brand/Container";

const stats = [
  { v: "100 hours of footage.", l: "Searched in seconds." },
  { v: "Up to 80% less time", l: "on tasks that used to take all day." },
  { v: "11 editing tools.", l: "One environment. Zero app switching." },
  { v: "Every AI edit is yours", l: "to change. Always." },
];

const benefits = [
  { icon: Zap, t: "Search first, scrub less", d: "Find exact moments from long-form footage in seconds with natural language." },
  { icon: Palette, t: "One pass, full polish", d: "Captions, filler cleanup, rhythm alignment, and structure happen together." },
  { icon: Users, t: "AI speed with human control", d: "Everything generated by AI remains editable on your real timeline." },
];

export function Outcomes() {
  return (
    <Section>
      <Container>
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="mt-2 font-display text-3xl font-extrabold text-smoke sm:text-5xl">
            Product proof, <span className="text-pyromi">not promises.</span>
          </h2>
        </div>

        <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {stats.map((s, i) => (
            <motion.div
              key={s.l}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.08 }}
              className="gradient-border rounded-2xl bg-charcoal/80 p-7 text-center"
            >
              <div className="font-display text-2xl font-extrabold leading-tight text-pyromi sm:text-3xl">
                {s.v}
              </div>
              <div className="mt-2 text-sm text-smoke/70">{s.l}</div>
            </motion.div>
          ))}
        </div>

        <div className="mt-10 grid gap-6 sm:grid-cols-3">
          {benefits.map((b) => {
            const Icon = b.icon;
            return (
              <div
                key={b.t}
                className="group gradient-border hover-pop rounded-2xl bg-charcoal/80 p-6"
              >
                <Icon
                  size={20}
                  className="text-solargold transition-transform duration-300 group-hover:scale-110"
                />
                <h3 className="mt-3 font-display font-bold text-smoke">{b.t}</h3>
                <p className="mt-1.5 text-sm text-smoke/60">{b.d}</p>
              </div>
            );
          })}
        </div>
      </Container>
    </Section>
  );
}
